#!/usr/bin/env bash
# =============================================================================
# HoneyAegis Raspberry Pi One-Click Setup
# =============================================================================
# Installs Docker, pulls pre-built ARM64 images, generates passwords,
# and starts a sensor-only HoneyAegis deployment on a Raspberry Pi.
#
# Usage:
#   curl -sSL https://raw.githubusercontent.com/thesecretchief/HoneyAegis/main/scripts/rpi-setup.sh | bash
#
# Tested on:
#   - Raspberry Pi OS Lite (64-bit) — Bookworm
#   - Ubuntu Server 24.04 (arm64)
# =============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

REPO_URL="https://github.com/thesecretchief/HoneyAegis.git"
INSTALL_DIR="${HOME}/HoneyAegis"

log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[x]${NC} $*" >&2; }
info() { echo -e "${CYAN}[*]${NC} $*"; }

# -----------------------------------------------------------------------------
# Pre-flight checks
# -----------------------------------------------------------------------------
check_arch() {
    local arch
    arch=$(uname -m)
    if [[ "$arch" != "aarch64" && "$arch" != "arm64" ]]; then
        err "This script is designed for ARM64 (Raspberry Pi 4/5)."
        err "Detected architecture: $arch"
        err "For x86_64 servers, use the standard install.sh instead."
        exit 1
    fi
    log "Architecture: $arch"
}

check_os() {
    if [[ ! -f /etc/os-release ]]; then
        err "Cannot detect OS. This script requires Debian/Ubuntu-based systems."
        exit 1
    fi
    # shellcheck disable=SC1091
    source /etc/os-release
    log "OS: $PRETTY_NAME"
}

check_memory() {
    local total_mb
    total_mb=$(awk '/MemTotal/ {printf "%.0f", $2/1024}' /proc/meminfo)
    if [[ "$total_mb" -lt 1800 ]]; then
        err "Insufficient RAM: ${total_mb}MB detected (minimum: 2GB)"
        err "HoneyAegis light profile requires at least 2GB RAM."
        exit 1
    fi
    log "RAM: ${total_mb}MB"
}

check_storage() {
    local avail_gb
    avail_gb=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
    if [[ "$avail_gb" -lt 8 ]]; then
        warn "Low disk space: ${avail_gb}GB available (recommended: 16GB+)"
    else
        log "Disk: ${avail_gb}GB available"
    fi
}

# -----------------------------------------------------------------------------
# Install Docker
# -----------------------------------------------------------------------------
install_docker() {
    if command -v docker &>/dev/null; then
        log "Docker already installed: $(docker --version)"
        return
    fi

    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh

    # Add current user to docker group
    if [[ "$(id -u)" -ne 0 ]]; then
        sudo usermod -aG docker "$USER"
        warn "Added $USER to docker group. You may need to log out and back in."
    fi

    # Enable on boot
    sudo systemctl enable docker
    sudo systemctl start docker

    log "Docker installed: $(docker --version)"
}

check_docker_compose() {
    if docker compose version &>/dev/null; then
        log "Docker Compose: $(docker compose version --short)"
    else
        err "Docker Compose v2 not found. Please update Docker."
        exit 1
    fi
}

# -----------------------------------------------------------------------------
# Generate secure passwords
# -----------------------------------------------------------------------------
generate_password() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
}

# -----------------------------------------------------------------------------
# Clone and configure
# -----------------------------------------------------------------------------
clone_repo() {
    if [[ -d "$INSTALL_DIR" ]]; then
        warn "HoneyAegis already exists at $INSTALL_DIR"
        info "Pulling latest changes..."
        cd "$INSTALL_DIR" && git pull origin main
    else
        info "Cloning HoneyAegis..."
        git clone "$REPO_URL" "$INSTALL_DIR"
    fi
    cd "$INSTALL_DIR"
    log "HoneyAegis cloned to $INSTALL_DIR"
}

configure_env() {
    if [[ -f .env ]]; then
        warn ".env already exists — skipping generation"
        return
    fi

    local pg_pass admin_pass redis_pass jwt_secret secret_key
    pg_pass=$(generate_password)
    admin_pass=$(generate_password)
    redis_pass=$(generate_password)
    jwt_secret=$(generate_password)
    secret_key=$(generate_password)

    cat > .env << EOF
# HoneyAegis Configuration (auto-generated by rpi-setup.sh)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# App
HONEYAEGIS_ENV=production
HONEYAEGIS_DEBUG=false
HONEYAEGIS_SECRET_KEY=$secret_key

# PostgreSQL
POSTGRES_DB=honeyaegis
POSTGRES_USER=honeyaegis
POSTGRES_PASSWORD=$pg_pass

# Redis
REDIS_PASSWORD=$redis_pass

# JWT
JWT_SECRET_KEY=$jwt_secret
JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60

# Admin (change after first login!)
ADMIN_EMAIL=admin@honeyaegis.local
ADMIN_PASSWORD=$admin_pass

# Ollama (disabled on RPi by default — requires 4GB+ RAM)
OLLAMA_ENABLED=false

# Ports
COWRIE_EXTERNAL_SSH_PORT=2222
COWRIE_EXTERNAL_TELNET_PORT=2223
BACKEND_PORT=8000
FRONTEND_PORT=3000
EOF

    log "Generated .env with secure random passwords"

    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  ${GREEN}HoneyAegis Admin Credentials${NC}                                ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  Email:    admin@honeyaegis.local                            ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  Password: ${YELLOW}${admin_pass}${NC}  ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}                                                              ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  ${RED}Save these credentials! They won't be shown again.${NC}          ${CYAN}║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# -----------------------------------------------------------------------------
# Optimize for RPi
# -----------------------------------------------------------------------------
optimize_rpi() {
    info "Applying Raspberry Pi optimizations..."

    # Increase swap (useful for 2GB models)
    if [[ -f /etc/dphys-swapfile ]]; then
        local current_swap
        current_swap=$(grep "^CONF_SWAPSIZE" /etc/dphys-swapfile 2>/dev/null | cut -d= -f2 || echo "100")
        if [[ "$current_swap" -lt 1024 ]]; then
            warn "Current swap: ${current_swap}MB. Consider increasing to 1024MB for stability."
            info "Run: sudo sed -i 's/CONF_SWAPSIZE=.*/CONF_SWAPSIZE=1024/' /etc/dphys-swapfile && sudo systemctl restart dphys-swapfile"
        fi
    fi

    # Enable Docker auto-start
    sudo systemctl enable docker 2>/dev/null || true

    log "RPi optimizations applied"
}

# -----------------------------------------------------------------------------
# Deploy
# -----------------------------------------------------------------------------
deploy() {
    info "Pulling Docker images (this may take a few minutes on RPi)..."
    docker compose pull 2>/dev/null || true

    info "Starting HoneyAegis (light profile)..."
    docker compose up -d

    # Wait for health
    info "Waiting for services to start..."
    local retries=0
    while [[ $retries -lt 30 ]]; do
        if docker compose ps | grep -q "healthy"; then
            break
        fi
        sleep 2
        retries=$((retries + 1))
    done

    log "HoneyAegis is running!"
}

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
print_summary() {
    local ip
    ip=$(hostname -I | awk '{print $1}')

    echo ""
    echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   ${CYAN}HoneyAegis RPi Sensor — Deployment Complete${NC}               ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   Dashboard:  http://${ip}:3000                          ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   API:        http://${ip}:8000/health                   ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   SSH Trap:   ${ip}:2222                                 ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   Telnet Trap:${ip}:2223                                 ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}   Useful commands:                                           ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}     docker compose ps        — check service status          ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}     docker compose logs -f    — stream logs                  ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}     docker stats --no-stream  — resource usage               ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}     ./scripts/update.sh       — update to latest version     ${GREEN}║${NC}"
    echo -e "${GREEN}║${NC}                                                              ${GREEN}║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
main() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}   HoneyAegis Raspberry Pi Setup v1.0.0                       ${CYAN}║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}"
    echo ""

    check_arch
    check_os
    check_memory
    check_storage

    install_docker
    check_docker_compose

    clone_repo
    configure_env
    optimize_rpi
    deploy
    print_summary
}

main "$@"
