apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.auth.password | quote }}
  app-secret-key: {{ .Values.env.HONEYAEGIS_SECRET_KEY | quote }}
  jwt-secret-key: {{ .Values.env.JWT_SECRET_KEY | quote }}
  admin-password: {{ .Values.env.ADMIN_PASSWORD | quote }}
